repos:
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.0.0
    hooks:
    - id: pip-compile
      name: pip-compile app
      description: This hook freezes production dependencies.
      files: ^requirements/app\.(in|txt)$
      args: [--output-file=requirements/app.txt, requirements/app.in]
    - id: pip-compile
      name: pip-compile dev
      description: This hook freezes developer dependencies.
      files: ^requirements/dev\.(in|txt)$
      args: [--output-file=requirements/dev.txt, requirements/dev.in]
    - id: pip-compile
      name: pip-compile test
      description: This hook freezes test dependencies.
      files: ^requirements/test\.(in|txt)$
      args: [--output-file=requirements/test.txt, requirements/test.in]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      name: flake8 (code linting)
      language_version: python3.8
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      name: black (code formatting)
      language_version: python3.8
-   repo: local
    hooks:
    - id: mypy
      name: mypy (static typing)
      pass_filenames: false
      language: script
      entry: ci/run_mypy.sh
      verbose: true
