name: lint-and-test

on: push


jobs:
  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py_version: [ '3.9' ]
    name: "Test (on Python ${{ matrix.py_version }})"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py_version }}
      - uses: actions/checkout@v2
      - run: ci/SETUP.sh
      - run: make test
    env:
      PGHOST: 127.0.0.1
      PGPORT: 5432
      PGUSER: flexmeasures_test
      PGDB: flexmeasures_test
      PGPASSWORD: flexmeasures_test

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12.5 
        env:
          POSTGRES_USER: flexmeasures_test
          POSTGRES_PASSWORD: flexmeasures_test
          POSTGRES_DB: flexmeasures_test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
